# Generated by Django 5.0.4 on 2024-05-28 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0001_initial'),
        ('semester', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='subject',
            fields=[
                ('sub_code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('implement_year', models.CharField(max_length=255)),
                ('syallabus', models.FileField(upload_to='')),
                ('sub_type', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='faculty.faculty')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='semester.semester')),
            ],
        ),
    ]
