# Generated by Django 5.0.4 on 2024-05-28 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '__first__'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('attid', models.IntegerField(primary_key=True, serialize=False)),
                ('attendance_date', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('stuid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.students')),
                ('sub_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='subject.subject')),
            ],
        ),
    ]
