# Generated by Django 5.0.4 on 2024-05-29 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Year', '0001_initial'),
        ('faculty', '0001_initial'),
        ('semester', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('Is_verified', models.BooleanField(default=False)),
                ('Year', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Year.yearmodel')),
                ('faculty', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='faculty.faculty')),
                ('semester', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='semester.semester')),
            ],
        ),
    ]
