# Generated by Django 5.0.4 on 2024-06-14 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_unverifiedstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='Is_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
